job/urls.py
from django.urls import path
from . import views
from . import api

app_name = 'job'
urlpatterns = [
    path('',views.Job_List_view,name='Job_List'),
    path('add/',views.add_job,name='add_job'),
    path('<str:slug>/',views.Job_Details_view,name='Job_Details'),
    #api
    path('api/list',api.job_list_api,name='job_list_api'),
    path('api/jobs/<int:id>',api.job_detail_api,name='job_detail_api'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('contact/', include('contact.urls',namespace='contact')),
    path('admin/', admin.site.urls),
    path('job/', include('job.urls',namespace='job')),
    path('api-auth/', include('rest_framework.urls'))
]

#Serving static files during development¶
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#Serving files uploaded by a user during development¶
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
# Create your models here.

#Job_Type
JOB_TYPE = (
    ('Full time','Full Time'),
    ('Part time','Part Time'),
)
#rename upload image
def image_rename(instance,filename):
    image_name , extension = filename.split('.')
    new_filename = "job/%s/%s.%s" % (instance.id, instance.id, extension)
    return new_filename
class Job(models.Model):
    owner =  models.ForeignKey(User,related_name='job_owner',on_delete=models.CASCADE)
    title = models.CharField(max_length=100,blank=False,null=False)
    job_type = models.CharField(max_length=15,choices=JOB_TYPE,blank=False,null=False)
    description = models.TextField(max_length=999,blank=False,null=False,default='Write a description')
    created_at = models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField(default=1,null=False,blank=False)
    salary = models.IntegerField(default=0,null=False,blank=False)
    experiences = models.IntegerField(default=1,null=False,blank=False)
    category = models.ForeignKey('Category',on_delete=models.CASCADE,null=True,blank=False)
    image = models.ImageField(upload_to=image_rename,blank=True,null=True)
    slug = models.SlugField(null=True,blank=True)
    
    def __str__(self):
        return self.title
    #auto save slug as title
    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
    
class Category(models.Model):
    name = models.CharField(max_length=25,blank=False,null=False)
    
    def __str__ (self):
        return self.name
    
    

class Apply(models.Model):
    job = models.ForeignKey(Job,related_name='apply_job',on_delete=models.CASCADE)
    name = models.CharField(max_length=30,blank=False,null=False)    
    email = models.EmailField(max_length=30,blank=False,null=False)
    portfolio_url = models.URLField(max_length=200,blank=True,null=True)
    cover_letter = models.TextField(max_length=340,blank=True,null=True)    
    cv_upload = models.FileField(upload_to='apply/',max_length=340,blank=True,null=True,default='Choice file')    
    
    def __str__(self):
        return self.name

job/views.py
from django.contrib import messages
from django.shortcuts import render,redirect
from django.urls import reverse
from .models import Job
from .form import apply_form ,add_job_form
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .filters import Job_Filter
# Create your views here.
#Job_List

def Job_List_view(request):
    job_list = Job.objects.all()
    #flitter
    my_filter = Job_Filter(request.GET,queryset=Job.objects.all())
    job_list = my_filter.qs
    paginator = Paginator(job_list, 2)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context={'job_list':page_obj,'job_num':job_list,'my_filter':my_filter}
    return render(request,'./job/jobs.html',context)
    

def Job_Details_view(request,slug):
    job_details = Job.objects.get(slug=slug)
    if request.method=='POST':
        form = apply_form(request.POST,request.FILES)
        if form.is_valid():
            my_form = form.save(commit=False)
            my_form.job = job_details
            my_form.save()
            messages.success(request,"You have been successfully Apply.")
            return redirect('job:Job_List')
        else:
            messages.error(request,"There was an error during apply")
    else:
        form = apply_form()
    context = {'job_details':job_details,'form':form}
    return render(request,'./job/job_details.html',context)

@login_required
def add_job(request):
    if request.method=='POST':
        form = add_job_form(request.POST,request.FILES)
        if form.is_valid():
            my_form = form.save(commit=False)
            my_form.owner = request.user
            my_form.save()
            messages.success(request,'Your job post has been added successfully')
            return redirect(reverse('job:Job_List'))
        else:
            messages.error(request,'something went wrong')
            redirect('job:add_job')
    else:
        form = add_job_form()
    context = {'form':form}
    return render(request,'./job/add_job.html',context)

job/templates/job/add_job.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Add New Job</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Add a New Job </h4>
                        <form method="POST" enctype='multipart/form-data'>
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    {{form.title | as_crispy_field}}   
                                </div>
                                <div class="col-md-12">
                                    {{form.job_type | as_crispy_field}}   
                                </div>
                                <div class="col-md-12">
                                    {{form.description | as_crispy_field}}   
                                </div>
                                <div class="col-md-12">
                                    {{form.vacancy | as_crispy_field}}   
                                </div>
                                <div class="col-md-12">
                                    {{form.salary | as_crispy_field}}                                      
                                </div>
                                <div class="col-md-12">
                                    {{form.experiences | as_crispy_field}}                                      
                                </div>
                                <div class="col-md-12">
                                    {{form.category | as_crispy_field}}                                      
                                </div>
                                <div class="col-md-12">
                                    {{form.image | as_crispy_field}}                                      
                                </div>
                                <div class="col-md-12 mt-5">
                                    <div class="submit_btn">
                                        <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

job/templates/job/job_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job_details.category}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="{{job_details.image.url}}" width="50" height="50" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job_details}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i>{{job_details.job_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{job_details.description}}</p>
                        </div>
                        <div class="single_wrap">
                            <h4>Responsibility</h4>
                            <ul>
                                <li>The applicants should have experience in the following areas.
                                </li>
                                <li>Have sound knowledge of commercial activities.</li>
                                <li>Leadership, analytical, and problem-solving abilities.</li>
                                <li>Should have vast knowledge in IAS/ IFRS, Company Act, Income Tax, VAT.</li>
                            </ul>
                        </div>
                        <div class="single_wrap">
                            <h4>Qualifications</h4>
                            <ul>
                                <li>The applicants should have experience in the following areas.
                                </li>
                                <li>Have sound knowledge of commercial activities.</li>
                                <li>Leadership, analytical, and problem-solving abilities.</li>
                                <li>Should have vast knowledge in IAS/ IFRS, Company Act, Income Tax, VAT.</li>
                            </ul>
                        </div>
                        <div class="single_wrap">
                            <h4>Benefits</h4>
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing.</p>
                        </div>
                    </div>
                    {% if request.user.is_authenticated %}
                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                        <form method="POST" enctype='multipart/form-data'>
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    {{form.name | as_crispy_field}}   
                                </div>
                                <div class="col-md-12">
                                    {{form.email | as_crispy_field}}   
                                </div>
                                <div class="col-md-12">
                                    {{form.portfolio_url | as_crispy_field}}   
                                </div>
                                <div class="col-md-12">
                                    {{form.cv_upload | as_crispy_field}}   
                                </div>
                                <div class="col-md-12">
                                    {{form.cover_letter | as_crispy_field}}                                      
                                </div>
                                <div class="col-md-12">
                                    <div class="submit_btn">
                                        <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    {% else %}
                    <div class="alert alert-warning mt-5" role="alert">
                        <h4 class="alert-heading">Login to Apply!</h4>
                        <p>You cannot apply if you are not user in our community to apply regist or login .</p>
                        <hr>
                        <p class="mb-0">Good Luck</p>
                    </div>
                    {% endif %}
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job_details.created_at}}</span></li>
                                <li>Vacancy: <span>{{job_details.vacancy}}</span></li>
                                <li>Salary: <span>{{job_details.salary}}K</span></li>
                                <li>Location: <span>California, USA</span></li>
                                <li>Job Nature: <span> {{job_details.job_type}}</span></li>
                                <li>Job Category: <span> {{job_details.category}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

job/templates/job/jobs.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job_num|length}}+ Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form action="#">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            {% bootstrap_form my_filter.form %}
                                        </div>
                                    </div>
                                </div>
                                <div class = 'd-flex justify-content-center m-5'>
                                    <button type="submit" class="btn btn-success">Search</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="job_lists m-0">
{% for job in job_list%}
                        <div class="row">
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        {% if job.image %}
                                        <div class="thumb">
                                            <img src="{{job.image.url}}" width="50" height="50" alt="">
                                        </div>
                                        {%endif%}
                                        <div class="jobs_conetent">
                                            <a href="{% url 'job:Job_Details' job.slug %}"><h4>{{job.title}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'job:Job_Details' job.slug  %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>{{job.created_at|date:'d M o'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
{% endfor %}
{% if job_list.has_other_pages %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if job_list.has_previous %}
                                        <li><a href="?page={{job_list.previous_page_number}}"><i class="ti-angle-left"></i> </a></li>
                                        {% endif %}
                                        {% for page_num in job_list.paginator.page_range  %}
                                        <li><a href="?page={{page_num}}"><span>{{page_num}}</span></a></li>
                                        {% endfor %}
                                        {% if job_list.has_next %}
                                        <li><a href="?page={{job_list.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
{% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}